version: '3.9'

services:
  # Сервис для Django-приложения
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 task_3.wsgi:application