# Generated by Django 4.2.19 on 2025-02-12 11:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 14, 13, 41, 946538), verbose_name='expired time'),
        ),
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='value',
            field=models.UUIDField(default=uuid.UUID('0322325b-543b-4a54-9d26-f29835559034')),
        ),
    ]
