# Generated by Django 4.2.19 on 2025-02-12 12:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_myrefreshtoken_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 15, 5, 43, 362252), verbose_name='expired time'),
        ),
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='value',
            field=models.UUIDField(default=uuid.UUID('3a7b92bd-515a-4bce-be90-f6451769b492')),
        ),
    ]
