# Generated by Django 4.2.19 on 2025-02-12 12:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_myrefreshtoken_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 15, 36, 28, 203060), verbose_name='expired time'),
        ),
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='value',
            field=models.UUIDField(default=uuid.UUID('249d6d8a-3e6a-45dd-9773-83692070a16a')),
        ),
    ]
