# Generated by Django 4.2.19 on 2025-02-12 15:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_myrefreshtoken_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 18, 20, 18, 50195), verbose_name='expired time'),
        ),
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='value',
            field=models.UUIDField(default=uuid.UUID('bea0aa67-85f8-4c38-bb9b-1e10853f41b0')),
        ),
    ]
